=== isuhao/openclonk-debian/docs/clonk.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!ENTITY % text "a | img | emlink | funclink | em | code | strong">

<!ELEMENT funcs (func+, (author, date)+)>
  <!ELEMENT func           (title, deprecated?, category, subcat*, version, deprecated?, syntax, desc, remark*, examples?, related?)>
    <!ELEMENT title        (#PCDATA)>
    <!ELEMENT category     (#PCDATA)>
    <!ELEMENT subcat       (#PCDATA)>
    <!ELEMENT version      (#PCDATA | extversion)*>
      <!ELEMENT extversion (#PCDATA)>
    <!ELEMENT deprecated   EMPTY>
    <!ELEMENT internal     EMPTY>
    <!ELEMENT syntax       (rtype, params*)>
      <!ELEMENT rtype      (#PCDATA)>
      <!ELEMENT params     (#PCDATA | param)*>
        <!ELEMENT param    (type?, optional?, name, optional?, desc, optional?)>
          <!ELEMENT name   (#PCDATA)>
          <!ELEMENT type   (#PCDATA)>
          <!ELEMENT desc   (#PCDATA | br | ul | li | table | %text;)*>
          <!ELEMENT optional EMPTY>
    <!ELEMENT remark       (#PCDATA | br | ul | li | table | %text;)*>
    <!ELEMENT examples     (example+)>
      <!ELEMENT example    (code | text)*>
        <!ELEMENT code     (#PCDATA | funclink | emlink | em | strong)*>
        <!ELEMENT text     (#PCDATA | br | ul | li | table | %text;)*>
    <!ELEMENT related      (funclink | emlink)+>
      <!ELEMENT funclink   (#PCDATA)>
      <!ELEMENT emlink     (#PCDATA)>
        <!ATTLIST emlink href CDATA #REQUIRED>
  <!ELEMENT author         (#PCDATA)>
  <!ELEMENT date           (#PCDATA)>
<!ELEMENT doc (title, (h | text | dl | part | code | author | date | img)*)>
  <!ELEMENT part (h | text | part | code | dl)*>

<!ELEMENT br EMPTY>

<!ELEMENT table (#PCDATA | caption | rowh | row | bitmask)*>
  <!ELEMENT caption (#PCDATA)>
    <!ATTLIST caption
      id ID #IMPLIED>
  <!ELEMENT row   (#PCDATA | col | literal_col)*>
    <!ATTLIST row
      id ID #IMPLIED>
  <!ELEMENT rowh  (#PCDATA | col | literal_col)*>
  <!ELEMENT col   (#PCDATA | %text;)*>
    <!ATTLIST col
      colspan CDATA #IMPLIED>
  <!ELEMENT literal_col   (#PCDATA | %text;)*>
    <!ATTLIST literal_col
      colspan CDATA #IMPLIED>
  <!ELEMENT bitmask (#PCDATA)>

<!ELEMENT ul    (#PCDATA | li)*>
  <!ELEMENT li    (#PCDATA | br | %text;)*>

<!ELEMENT dl    (#PCDATA | dd | dt)*>
  <!ELEMENT dt    (#PCDATA | br | %text;)*>
    <!ATTLIST dt
      id ID #IMPLIED>
  <!ELEMENT dd    (#PCDATA | text | code)*>

<!ELEMENT em    (#PCDATA)>
<!ELEMENT strong (#PCDATA)>

<!ELEMENT h     (#PCDATA)>
  <!ATTLIST h
    id ID #IMPLIED>

<!ELEMENT img   EMPTY>
  <!ATTLIST img
    src CDATA #REQUIRED
    width CDATA "0"
    height CDATA "0"
    id ID #IMPLIED>

<!ELEMENT a     (#PCDATA)>
  <!ATTLIST a
    href CDATA #REQUIRED>

=== isuhao/openclonk-debian/docs/sdk/script/fn/SetObjectOrder.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE funcs
  SYSTEM '../../../clonk.dtd'>
<?xml-stylesheet type="text/xsl" href="../../../clonk.xsl"?>
<funcs>
  <func>
    <title>SetObjectOrder</title>
    <category>Objects</category>
    <subcat>Position</subcat>
    <version>4.9.1.0 GWE<extversion>4.9.5.0 CE</extversion></version>
    <syntax>
      <rtype>bool</rtype>
      <params>
        <param>
          <type>object</type>
          <name>object_before_or_after</name>
          <desc>Object before or after which sort_object is to be inserted.</desc>
        </param>
        <param>
          <type>object</type>
          <name>sort_object</name>
          <desc>Object which is to be inserted before or after pObjBefore. Can be 0 in local calls.</desc>
          <optional />
        </param>
        <param>
          <type>bool</type>
          <name>after</name>
          <desc>If not 0, sort_object will be inserted after object object_before_or_after (and not before).</desc>
          <optional />
        </param>
      </params>
    </syntax>
    <desc>Ensures that an object is internally sorted before or after another specified object. In this way, you can e.g. ensure that an elevator case is always drawn and processed before its elevator structure.</desc>
    <remark>You should only resort objects of the same category, otherwise the internal handling mights get confused.<br/>The actual resorting is done later but within the same frame as the script call.</remark>
    <examples>
      <example>
        <code>SetObjectOrder(<funclink>FindObject</funclink>(TRE1), <funclink>FindObject</funclink>(TRE2));</code>
        <text>Places the first found tree of type TRE2 before the first found tree of type TRE1.</text>
      </example>
    </examples>
    <related>
      <funclink>ResortObjects</funclink>
      <funclink>Resort</funclink>
    </related>
  </func>
  <author>Sven2</author><date>2002-04</date>
</funcs>

=== isuhao/openclonk-debian/docs/sdk/script/fn/SimFlight.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE funcs
  SYSTEM '../../../clonk.dtd'>
<?xml-stylesheet type="text/xsl" href="../../../clonk.xsl"?>
<funcs>
  <func>
    <title>SimFlight</title>
    <category>Objects</category>
    <subcat>Movement</subcat>
    <version>4.9.5.0 CE</version>
    <syntax>
      <rtype>bool</rtype>
      <params>
        <param>
          <type>int &amp;</type>
          <name>x</name>
          <desc>X coordinate of the starting position. Always global.</desc>
        </param>
        <param>
          <type>int &amp;</type>
          <name>y</name>
          <desc>Y coordinate of the starting position. Always global.</desc>
        </param>
        <param>
          <type>int &amp;</type>
          <name>xdir</name>
          <desc>Initial horizontal speed.</desc>
        </param>
        <param>
          <type>int &amp;</type>
          <name>ydir</name>
          <desc>Initial vertical speed.</desc>
        </param>
        <param>
          <type>int</type>
          <name>min_density</name>
          <desc>Mininum density of the material which will stop the projected trajectory. If not specified or 0 this will default to value 50 (solid material).</desc>
          <optional />
        </param>
        <param>
          <type>int</type>
          <name>max_density</name>
          <desc>Maximum density of the material which will stop the projected trajectory. If not specified or 0 this will default to value 50 (solid material).</desc>
          <optional />
        </param>
        <param>
          <type>int</type>
          <name>iterations</name>
          <desc>Number of simulated frames for which the projection runs. If not specified or 0 the simultion will run indefinitely until material or the limits of the landscape are encountered.</desc>
          <optional />
        </param>
        <param>
          <type>int</type>
          <name>precision</name>
          <desc>Precision. Default 10 if not specified or 0.</desc>
          <optional />
        </param>
      </params>
    </syntax>
    <desc>Simulates the motion of a falling object with a given starting position and initial speed. If the projected trajectory encounters a material of the specified density, the simulation will stop and the function will return 'true'. Otherwise the function will return 'false'. <br/> If the return value is 'true', the x and y coordinates of the point of interception will be stored in the specified variables for x and y, the horizontal and vertical speed at the time of interception in xdir and ydir respectively. See <emlink href="script/Funcs.html#referenzen">references</emlink> for details.</desc>
    <examples>
      <example>
        <code>var x = <funclink>GetX</funclink>(), y = <funclink>GetY</funclink>(), xdir = <funclink>GetXDir</funclink>(), ydir = <funclink>GetYDir</funclink>();
if (<funclink>GetAction</funclink>()eq&quot;Jump&quot;)
  if (SimFlight(x, y, xdir, ydir))
    if (ydir &gt;= 80)
      <funclink>Message</funclink>(&quot;Oh oh, das wird ein harter Aufprall!&quot;);</code>
        <text>If the calling clonk is situated in mid-air and it appears that he will hit the ground at high speed, he will call out.</text>
      </example>
    </examples>
  </func>
  <author>Newton</author><date>2004-03</date>
</funcs>

=== isuhao/openclonk-debian/docs/sdk/script/fn/DetachMesh.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE funcs
  SYSTEM '../../../clonk.dtd'>
<?xml-stylesheet type="text/xsl" href="../../../clonk.xsl"?>
<funcs>
  <func>
    <title>DetachMesh</title>
    <category>Objects</category>
    <subcat>Display</subcat>
    <version>4.10.0.0 OC</version>
    <syntax>
      <rtype>bool</rtype>
      <params>
        <param>
          <type>int</type>
          <name>attach_number</name>
          <desc>Number of the mesh to detach. <funclink>AttachMesh</funclink> returns such a number.</desc>
        </param>
      </params>
    </syntax>
    <desc>If a mesh was previously attached to another one via <funclink>AttachMesh</funclink> then it can be detached again using this function.</desc>
    <examples>
      <example>
        <code>func FxIntCarryBowStart(object target, int number)
{
	<funclink>EffectVar</funclink>(0, target, number) = target-&gt;<funclink>AttachMesh</funclink>(Bow, &quot;pos_hand1&quot;, &quot;main&quot;);
}

func FxIntCarryBowStop(object target, int number)
{
	target-&gt;<funclink>DetachMesh</funclink>(<funclink>EffectVar</funclink>(0, target, number));
}</code>
        <text>Script for an <emlink href="script/Effects.html">effect</emlink>: The effect target carries a bow as long as the effect remains active.</text>
      </example>
    </examples>
    <related><funclink>AttachMesh</funclink></related>
  </func>
  <author>Clonk-Karl</author><date>2010-04</date>
</funcs>

=== isuhao/openclonk-debian/docs/sdk/script/fn/SetSolidMask.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE funcs
  SYSTEM '../../../clonk.dtd'>
<?xml-stylesheet type="text/xsl" href="../../../clonk.xsl"?>
<funcs>
  <func>
    <title>SetSolidMask</title>
    <category>Objects</category>
    <subcat>Status</subcat>
    <version>4.6.5.0 CP</version>
    <syntax>
      <rtype>void</rtype>
      <params>
        <param>
          <type>int</type>
          <name>x</name>
          <desc>X position of the top left corner of the new SolidMask rectangle within the definition graphic.</desc>
        </param>
        <param>
          <type>int</type>
          <name>y</name>
          <desc>Y position of the top left corner of the new SolidMask rectangle within the definition graphic.</desc>
        </param>
        <param>
          <type>int</type>
          <name>width</name>
          <desc>Width of the new SolidMask rectangle within the definition graphic.</desc>
        </param>
        <param>
          <type>int</type>
          <name>height</name>
          <desc>Height of the new SolidMask rectangle within the definition graphic.</desc>
        </param>
        <param>
          <type>int</type>
          <name>target_x</name>
          <desc>X target position of the SolidMask relative to the top left corner of the object graphic.</desc>
        </param>
        <param>
          <type>int</type>
          <name>target_y</name>
          <desc>Y target position of the SolidMask relative to the top left corner of the object graphic.</desc>
        </param>
      </params>
    </syntax>
    <desc>Sets the solid area of an object. The source rectangle determines which pixels from the definition graphic should be used. All pixels within the rectangle of less than 50% transparency will be solid. Also see the SolidMask entry in <emlink href="definition/defcore.html">DefCore.txt</emlink>.</desc>
    <remark>Solid areas will internally be drawn in the landscape using the "Vehicle" material.</remark>
    <examples>
      <example>
        <code>SetSolidMask();</code>
        <text>Removes the SolidMask for the calling object.</text>
      </example>
    </examples>
  </func>
  <author>Sven2</author><date>2003-06</date>
</funcs>

=== isuhao/openclonk-debian/docs/sdk/script/fn/C4V_String.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE funcs
  SYSTEM '../../../clonk.dtd'>
<?xml-stylesheet type="text/xsl" href="../../../clonk.xsl"?>
<funcs>
  <func>
    <title>C4V_String</title>
    <category>Variables</category>
    <version>4.9.1.0 GWE</version>
    <syntax><rtype>int</rtype></syntax>
    <desc>Data type: string.</desc>
    <remark>This value is also defined as a constant. Thus the parameter brackets can be omitted.</remark>
    <examples>
      <example>
        <code><funclink>if</funclink> (x &amp;&amp; <funclink>GetType</funclink>(x)==C4V_String) <funclink>Log</funclink>(&quot;x=%s&quot;, x);</code>
        <text>Writes x to the log if it is a string.</text>
      </example>
    </examples>
    <related><funclink>GetType</funclink></related>
  </func>
  <author>Sven2</author><date>2002-04</date>
</funcs>

=== isuhao/openclonk-debian/docs/sdk/script/fn/Split2Components.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE funcs
  SYSTEM '../../../clonk.dtd'>
<?xml-stylesheet type="text/xsl" href="../../../clonk.xsl"?>
<funcs>
  <func>
    <title>Split2Components</title>
    <category>Objects</category>
    <subcat>Existence</subcat>
    <version>4.6.5.0 CP</version>
    <syntax>
      <rtype>bool</rtype>
      <params>
        <param>
          <type>object</type>
          <name>obj</name>
          <desc>Object to be split. Can be 0 in local calls.</desc>
          <optional />
        </param>
      </params>
    </syntax>
    <desc>Splits an object into its components. The new component objects will be created with random rotation and a low speed in random direction at the position at which the object was located. The original object is removed. If the original object was contained, the new component objects will be created in the original container.</desc>
    <remark>See notice for <funclink>RemoveObject</funclink>.</remark>
    <examples>
      <example>
        <code>protected func ControlDigDouble()
  {
  var target=<funclink>Contents</funclink>();
  <funclink>if</funclink> (!target) <funclink>return</funclink>();
  Split2Components(target);
  return true;
  }</code>
        <text>Script for a clonk: He splits the first object he carries on double dig.</text>
      </example>
    </examples>
    <related>
      <funclink>RemoveObject</funclink>
      <funclink>GetComponent</funclink>
    </related>
  </func>
  <author>Sven2</author><date>2002-08</date>
</funcs>

=== isuhao/openclonk-debian/docs/sdk/script/fn/FindContents.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE funcs
  SYSTEM '../../../clonk.dtd'>
<?xml-stylesheet type="text/xsl" href="../../../clonk.xsl"?>
<funcs>
  <func>
    <title>FindContents</title>
    <category>Objects</category>
    <subcat>Search</subcat>
    <version>4.6.5.0 CP</version>
    <syntax>
      <rtype>object</rtype>
      <params>
        <param>
          <type>id</type>
          <name>type</name>
          <desc>Object type to be found.</desc>
        </param>
      </params>
    </syntax>
    <desc>Returns the first found contained object of the specified type.</desc>
    <examples>
      <example>
        <code>var hut;
<funclink>if</funclink> (hut=<funclink>FindObject</funclink>(HUT2)) hut-&gt;FindContents(Clonk)-&gt;<funclink>Exit</funclink>(hut-&gt;<funclink>GetX</funclink>(), hut-&gt;<funclink>GetY</funclink>());</code>
        <text>Expels a clonk from a hut.</text>
      </example>
    </examples>
    <related>
      <funclink>FindOtherContents</funclink>
      <funclink>Contents</funclink>
      <funclink>FindObject</funclink>
    </related>
  </func>
  <author>Sven2</author><date>2001-11</date>
</funcs>

=== isuhao/openclonk-debian/docs/sdk/script/fn/C4D_Object.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE funcs
  SYSTEM '../../../clonk.dtd'>
<?xml-stylesheet type="text/xsl" href="../../../clonk.xsl"?>
<funcs>
  <func>
    <title>C4D_Object</title>
    <category>Objects</category>
    <subcat>Category</subcat>
    <version>4.6.5.0 CP</version>
    <syntax><rtype>int </rtype></syntax>
    <desc>Object category: small item.</desc>
    <remark>This value is also defined as a constant. Thus the parameter brackets can be omitted.</remark>
    <examples>
      <example>
        <code><funclink>GetDefinition</funclink>(0, C4D_Object( ));</code>
        <text>Returns the id of the first loaded definition. Similar scripting is used in the research lab to list researchable object.</text>
      </example>
    </examples>
    <related>
      <funclink>GetCategory</funclink>
      <funclink>SetCategory</funclink>
      <funclink>GetHomebaseMaterial</funclink>
      <funclink>GetPlrKnowledge</funclink>
      <funclink>GetDefinition</funclink>
    </related>
  </func>
  <author>GÃ¼nther</author><date>2002-02</date>
</funcs>
