=== isuhao/openclonk-debian/docs/clonk.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!ENTITY % text "a | img | emlink | funclink | em | code | strong">

<!ELEMENT funcs (func+, (author, date)+)>
  <!ELEMENT func           (title, deprecated?, category, subcat*, version, deprecated?, syntax, desc, remark*, examples?, related?)>
    <!ELEMENT title        (#PCDATA)>
    <!ELEMENT category     (#PCDATA)>
    <!ELEMENT subcat       (#PCDATA)>
    <!ELEMENT version      (#PCDATA | extversion)*>
      <!ELEMENT extversion (#PCDATA)>
    <!ELEMENT deprecated   EMPTY>
    <!ELEMENT internal     EMPTY>
    <!ELEMENT syntax       (rtype, params*)>
      <!ELEMENT rtype      (#PCDATA)>
      <!ELEMENT params     (#PCDATA | param)*>
        <!ELEMENT param    (type?, optional?, name, optional?, desc, optional?)>
          <!ELEMENT name   (#PCDATA)>
          <!ELEMENT type   (#PCDATA)>
          <!ELEMENT desc   (#PCDATA | br | ul | li | table | %text;)*>
          <!ELEMENT optional EMPTY>
    <!ELEMENT remark       (#PCDATA | br | ul | li | table | %text;)*>
    <!ELEMENT examples     (example+)>
      <!ELEMENT example    (code | text)*>
        <!ELEMENT code     (#PCDATA | funclink | emlink | em | strong)*>
        <!ELEMENT text     (#PCDATA | br | ul | li | table | %text;)*>
    <!ELEMENT related      (funclink | emlink)+>
      <!ELEMENT funclink   (#PCDATA)>
      <!ELEMENT emlink     (#PCDATA)>
        <!ATTLIST emlink href CDATA #REQUIRED>
  <!ELEMENT author         (#PCDATA)>
  <!ELEMENT date           (#PCDATA)>
<!ELEMENT doc (title, (h | text | dl | part | code | author | date | img)*)>
  <!ELEMENT part (h | text | part | code | dl)*>

<!ELEMENT br EMPTY>

<!ELEMENT table (#PCDATA | caption | rowh | row | bitmask)*>
  <!ELEMENT caption (#PCDATA)>
    <!ATTLIST caption
      id ID #IMPLIED>
  <!ELEMENT row   (#PCDATA | col | literal_col)*>
    <!ATTLIST row
      id ID #IMPLIED>
  <!ELEMENT rowh  (#PCDATA | col | literal_col)*>
  <!ELEMENT col   (#PCDATA | %text;)*>
    <!ATTLIST col
      colspan CDATA #IMPLIED>
  <!ELEMENT literal_col   (#PCDATA | %text;)*>
    <!ATTLIST literal_col
      colspan CDATA #IMPLIED>
  <!ELEMENT bitmask (#PCDATA)>

<!ELEMENT ul    (#PCDATA | li)*>
  <!ELEMENT li    (#PCDATA | br | %text;)*>

<!ELEMENT dl    (#PCDATA | dd | dt)*>
  <!ELEMENT dt    (#PCDATA | br | %text;)*>
    <!ATTLIST dt
      id ID #IMPLIED>
  <!ELEMENT dd    (#PCDATA | text | code)*>

<!ELEMENT em    (#PCDATA)>
<!ELEMENT strong (#PCDATA)>

<!ELEMENT h     (#PCDATA)>
  <!ATTLIST h
    id ID #IMPLIED>

<!ELEMENT img   EMPTY>
  <!ATTLIST img
    src CDATA #REQUIRED
    width CDATA "0"
    height CDATA "0"
    id ID #IMPLIED>

<!ELEMENT a     (#PCDATA)>
  <!ATTLIST a
    href CDATA #REQUIRED>

=== isuhao/openclonk-debian/docs/sdk/script/fn/CreateParticle.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE funcs
  SYSTEM '../../../clonk.dtd'>
<?xml-stylesheet type="text/xsl" href="../../../clonk.xsl"?>
<funcs>
  <func>
    <title>CreateParticle</title>
    <category>Particle</category>
    <version>5.1 OC</version>
    <syntax>
      <rtype>bool</rtype>
      <params>
        <param>
          <type>string</type>
          <name>szName</name>
          <desc>Name of the particle</desc>
        </param>
        <param>
          <type>int</type>
          <name>x</name>
          <desc>X coordinate of the particle. Offset in local calls.</desc>
        </param>
        <param>
          <type>int</type>
          <name>y</name>
          <desc>Y coordinate of the particle. Offset in local calls.</desc>
        </param>
        <param>
          <type>int</type>
          <name>xdir</name>
          <desc>Initial horizontal velocity of the particle.</desc>
        </param>
        <param>
          <type>int</type>
          <name>ydir</name>
          <desc>Initial vertical velocity of the particle.</desc>
        </param>
        <param>
          <type>int</type>
          <name>a</name>
          <desc>Extra parameter. This is usually the size of the particle in 1/5 pixels.</desc>
        </param>
        <param>
          <type>int</type>
          <name>b</name>
          <desc>Extra parameter. This is usually the color modulation of the particle.</desc>
        </param>
        <param>
          <type>object</type>
          <name>target</name>
          <desc>Target object for object local particles. Object local particles are drawn directly on top of the object and are removed when the object is deleted.</desc>
          <optional />
        </param>
        <param>
          <type>bool</type>
          <name>behind_target</name>
          <desc>If specified and not <code>false</code>, the particle is drawn directly behind the target object.</desc>
          <optional />
        </param>
      </params>
    </syntax>
    <desc>Creates a particle. The named particle definition must be loaded. For more information see the particle documentation.</desc>
    <remark>This function returns <code>false</code> if the particle definition was not found, otherwise <code>true</code>. There is no return value indicating whether the particle has actually been created. This must be so to prevent synchronization problems in network games, as particles may be handled differently on each computer in the network.</remark>
    <examples>
      <example>
        <code>CreateParticle(&quot;Blast&quot;, 0,0, 0,0, 100, <funclink>RGB</funclink>(128,128,255));</code>
        <text>Creates a blue explosion at the position of the calling object.</text>
      </example>
    </examples>
    <related>
      <funclink>PushParticles</funclink>
      <funclink>ClearParticles</funclink>
    </related>
  </func>
  <author>Sven2</author><date>2002-04</date>
</funcs>

=== isuhao/openclonk-debian/docs/sdk/script/fn/SetOwner.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE funcs
  SYSTEM '../../../clonk.dtd'>
<?xml-stylesheet type="text/xsl" href="../../../clonk.xsl"?>
<funcs>
  <func>
    <title>SetOwner</title>
    <category>Objects</category>
    <subcat>Status</subcat>
    <version>4.6.5.0 CP</version>
    <syntax>
      <rtype>bool</rtype>
      <params>
        <param>
          <type>int</type>
          <name>new_owner</name>
          <desc>Player number of the new owner. -1 for no owner.</desc>
        </param>
      </params>
    </syntax>
    <desc>Changes the owner of the object.</desc>
    <remark>This function also changes the controller to the new owner.</remark>
    <examples>
      <example>
        <code>protected func Entrance(container) { SetOwner(container-&gt;<funclink>GetOwner</funclink>()); <funclink>return</funclink>(); }</code>
        <text>This object changes its owner when it is collected.</text>
      </example>
    </examples>
    <related>
      <funclink>SetController</funclink>
      <funclink>GetOwner</funclink>
      <funclink>MakeCrewMember</funclink>
    </related>
  </func>
  <author>Sven2</author><date>2001-11</date>
</funcs>

=== isuhao/openclonk-debian/docs/sdk/script/fn/GetPathLength.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE funcs
  SYSTEM '../../../clonk.dtd'>
<?xml-stylesheet type="text/xsl" href="../../../clonk.xsl"?>
<funcs>
  <func>
    <title>GetPathLength</title>
    <category>Landscape</category>
    <version>4.9.1.0 GWE</version>
    <syntax>
      <rtype>int</rtype>
      <params>
        <param>
          <type>int</type>
          <name>startx</name>
          <desc>X coordinate of starting position</desc>
        </param>
        <param>
          <type>int</type>
          <name>starty</name>
          <desc>Y coordinate of starting position</desc>
        </param>
        <param>
          <type>int</type>
          <name>endx</name>
          <desc>X coordinate of end position</desc>
        </param>
        <param>
          <type>int</type>
          <name>endy</name>
          <desc>Y coordinate of end position</desc>
        </param>
      </params>
    </syntax>
    <desc>Searches for a path from start point to end point using the pathfinding algorithm as used by clonks and returns the length of the found path. Returns 0 if no path was found.</desc>
    <examples>
      <example>
        <code>var iDist = GetPathLength(<funclink>GetX</funclink>(), <funclink>GetY</funclink>(), <funclink>GetX</funclink>(<funclink>FindBase</funclink>(<funclink>GetOwner</funclink>())), <funclink>GetY</funclink>(<funclink>FindBase</funclink>(<funclink>GetOwner</funclink>())));</code>
        <text>Determines the distance from an object to its closest friendly base.</text>
      </example>
    </examples>
  </func>
  <author>PeterW</author><date>2002-04</date>
</funcs>

=== isuhao/openclonk-debian/docs/sdk/script/fn/SetFilmView.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE funcs
  SYSTEM '../../../clonk.dtd'>
<?xml-stylesheet type="text/xsl" href="../../../clonk.xsl"?>
<funcs>
  <func>
    <title>SetFilmView</title>
    <category>Player</category>
    <subcat>View</subcat>
    <version>4.9.1.0 GWE</version>
    <syntax>
      <rtype>int</rtype>
      <params>
        <param>
          <type>int</type>
          <name>for_player</name>
          <desc>Number of the player whose view is to be displayed.</desc>
        </param>
      </params>
    </syntax>
    <desc>Sets film playback view to the specified player.</desc>
    <examples>
      <example>
        <code>protected func InitializePlayer(player)
{
	<funclink>if</funclink> (<funclink>GetPlayerName</funclink>(player) eq &quot;Kamera&quot;) SetFilmView(player);
}</code>
        <text>This scenario script sets the playback view of the recorded round to the player with the name "Kamera".</text>
      </example>
    </examples>
  </func>
  <author>Sven2</author><date>2002-05</date>
</funcs>

=== isuhao/openclonk-debian/docs/sdk/folder/index.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE doc
  SYSTEM '../../clonk.dtd'>
<?xml-stylesheet type="text/xsl" href="../../clonk.xsl"?>
<doc>
  <title>Scenario Folder</title>
  <h id="Folders">Scenario Folder</h>
  <part>
    <text>Scenario folders are used to group a number of scenarios. Scenario folders are displayed with a book icon in the startup screen which can then be opened to list contained scenarios.</text>
    <h id="Components">Scenario Components (c4s)</h>
    <dl>
      <dt id="c4s"><img height="16" src="../../images/icon_scenario.gif" width="16"/><emlink href="scenario/index.html">*.c4s</emlink></dt>
      <dd>
        <text>Scenario folders can contain any number of scenarios.</text>
      </dd>
      <dt id="c4f"><img height="16" src="../../images/icon_scenario_folder.gif" width="16"/>*.c4f</dt>
      <dd>
        <text>Scenario folders can also contain other scenario folders.</text>
      </dd>
      <dt id="Title"><img height="16" src="../../images/icon_image.gif" width="16"/>Title.png/Title.bmp</dt>
      <dd>
        <text>The title picture of the scenario folder in png format. Size: 200x150 pixel. The older bmp format with 256 colors is still supported as well.</text>
      </dd>
      <dt id="Iconbmp"><img height="16" src="../../images/icon_image.gif" width="16"/>Icon.bmp/Icon.png</dt>
      <dd>
        <text>The icon of a scenario folder which is to be displayed instead of the book icon. BMP format (obsolete): 16x16 pixels, color RGB 255 0 255 (purple) is transparent. PNG format: 24x24 pixels, alpha channel is used for transparency.</text>
      </dd>
      <dt id="Desc__rtf"><img height="16" src="../../images/icon_text.gif" width="16"/>Desc*.rtf</dt>
      <dd>
        <text>The description text of the scenario in rich text format (rtf). '__' is to be replaced by the two digit language code, e.g. DE for German and US for American English. Multiple descriptions for several languages can be contained in a scenario file of which the game will automatically load the one appropriate for the configured language.</text>
        <text>The font of the description text is set internally on display. The character size in the file should be 10pt for headings and 8pt for text. Images or other rtf tags are ignored.</text>
        <text>It is recommended to edit this file using a small scale rtf editor such as WordPad.exe in Windows and not a full-blown word processor such as Word as these will stuff kilobytes of unneeded extra information into the rtf file.</text>
      </dd>
      <dt id="Titletxt"><img height="16" src="../../images/icon_text.gif" width="16"/>Title.txt</dt>
      <dd>
        <text>By default, the title of a scenario is set when renaming the scenario in the menu system and stored in section [Head] of Scenario.txt. The file name of the scenario group file may differ. For language dependent titles you should create a Title.txt component with the appropriate contents:</text>
        <code>DE:Meine Rundensammlung
US:My scenario collection</code>        <text>Important: No quotation marks and special characters should be used.</text>
      </dd>
      <dt id="FolderMaptxt"><img height="16" src="../../images/icon_text.gif" width="16"/><emlink href="folder/foldermap.html">FolderMap.txt</emlink></dt>
      <dd>
        <text>From CR, scenario folders can also contain graphical folder maps for the selection of scenarios.</text>
      </dd>
      <dt id="Loader"><img height="16" src="../../images/icon_image.gif" width="16"/>Loader*.png/Loader*.bmp</dt>
      <dd>
        <text>Scenario folders can contain local loader screens. Also see <emlink href="scenario/index.html">scenarios</emlink>. The <emlink href="scenario/index.html#UeberladungenC4S">overloading rules</emlink> apply.</text>
      </dd>
      <dt id="Materialc4g"><img height="16" src="../../images/icon_system.gif" width="16"/><emlink href="material/index.html">Material.c4g</emlink></dt>
      <dd>
        <text>Scenario folders can contain local material definitions. Also see <emlink href="scenario/index.html#Materialc4g">scenarios</emlink>. The <emlink href="scenario/index.html#UeberladungenC4S">overloading rules</emlink> apply.</text>
      </dd>
      <dt id="Graphicsc4g"><img height="16" src="../../images/icon_system.gif" width="16"/>Graphics.c4g</dt>
      <dd>
        <text>Scenario folders can overload individual entries of the global Graphics.c4g group. See <emlink href="#UeberladungenC4S">overloading rules</emlink>.</text>
      </dd>
      <dt id="Musicc4g"><img height="16" src="../../images/icon_system.gif" width="16"/>Music.c4g</dt>
      <dd>
        <text>Scenario folders can contain local music files. Also see <emlink href="scenario/index.html#Musicc4g">scenarios</emlink>. The <emlink href="scenario/index.html#UeberladungenC4S">overloading rules</emlink> apply.</text>
      </dd>
      <dt id="c4d"><img height="16" src="../../images/icon_object_definition.gif" width="16"/><emlink href="definition/index.html">*.c4d</emlink></dt>
      <dd>
        <text>Scenario folders can contain object definitions, which will then be available in all scenarios contained in the folder.Also see <emlink href="scenario/index.html#c4d">scenarios</emlink>. The <emlink href="scenario/index.html#UeberladungenC4S">overloading rules</emlink> apply.</text>
      </dd>
      <dt id="Infotxt"><img height="16" src="../../images/icon_text.gif" width="16"/>Info.txt</dt>
      <dd>
        <text>Here an author can store additional information about the development of his scenario, his email address, or other information he wants to share with other developers.</text>
      </dd>
      <dt id="Authortxt"><img height="16" src="../../images/icon_text.gif" width="16"/>Author.txt</dt>
      <dd>
        <text>Should contain the name of the author in format "Firstname Lastname (Nick)" and is used to maintain the name of the original author, if the scenario group file is edited by another developer at a later point in time. The name stored here is only displayed, however, if the scenario was edited by RedWolf Design. This feature is mainly used for contest scenarios.</text>
      </dd>
    </dl>
  </part>
  <author>Sven2</author><date>2006-09</date>
</doc>

=== isuhao/openclonk-debian/docs/sdk/script/fn/OCF_Container.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE funcs
  SYSTEM '../../../clonk.dtd'>
<?xml-stylesheet type="text/xsl" href="../../../clonk.xsl"?>
<funcs>
  <func>
    <title>OCF_Container</title>
    <category>Objects</category>
    <subcat>OCF</subcat>
    <version>4.6.5.0 CP</version>
    <syntax><rtype>int</rtype></syntax>
    <desc>Object character flag: the object is a container with theoreticall accessible contents (e.g. a building with entrance, transport vehicle...)</desc>
    <remark>This value is also defined as a constant. Thus the parameter brackets can be omitted.</remark>
    <remark>For more information and examples regarding these constants see <emlink href="definition/ocf.html">object character flags</emlink>.</remark>
    <related>
      <funclink>GetOCF</funclink>
      <funclink>FindObject</funclink>
      <emlink href="definition/ocf.html">Object character flags</emlink>
    </related>
  </func>
  <author>Sven2</author><date>2002-05</date>
</funcs>

=== isuhao/openclonk-debian/docs/sdk/script/fn/GetAnimationPosition.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE funcs
  SYSTEM '../../../clonk.dtd'>
<?xml-stylesheet type="text/xsl" href="../../../clonk.xsl"?>
<funcs>
  <func>
    <title>GetAnimationPosition</title>
    <category>Animations</category>
    <version>4.10.0.0 OC</version>
    <syntax>
      <rtype>int</rtype>
      <params>
        <param>
          <type>int</type>
          <name>animation_number</name>
          <desc>Animation number of the animation whose position to retrieve.</desc>
        </param>
      </params>
    </syntax>
    <desc>Retuerns the position of the animation refered to by the given number. The returned value lies between 0 and <funclink>GetAnimationLength</funclink>(<funclink>GetAnimationName</funclink>(animation_number)). If there is no such animation with the given number or the number refers to a combination node then this function returns nil.</desc>
    <remark>See the <emlink href="definition/animations.html">animation documentation</emlink> for further explanations of the animation system.</remark>
    <examples>
      <example>
        <code><funclink>SetAnimationPosition</funclink>(animation_number, <funclink>Anim_Const</funclink>(<funclink>GetAnimationPosition</funclink>(animation_number)+100));</code>
        <text>Script for a timer: For each call the animation is advanced by 100 milliseconds. If the timer is called periodically in same intervals <funclink>Anim_Linear</funclink> can be used instead.</text>
      </example>
    </examples>
    <related>
      <funclink>PlayAnimation</funclink>
      <funclink>SetAnimationPosition</funclink>
      <funclink>GetAnimationWeight</funclink>
      <funclink>SetAnimationWeight</funclink>
    </related>
  </func>
  <author>Clonk-Karl</author><date>2010-01</date>
</funcs>

=== isuhao/openclonk-debian/docs/sdk/script/fn/GetValue.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE funcs
  SYSTEM '../../../clonk.dtd'>
<?xml-stylesheet type="text/xsl" href="../../../clonk.xsl"?>
<funcs>
  <func>
    <title>GetValue</title>
    <category>Objects</category>
    <subcat>Status</subcat>
    <version>4.6.5.0 CP<extversion>4.9.1.0 GWE</extversion></version>
    <syntax>
      <rtype>int</rtype>
      <params>
        <param>
          <type>object</type>
          <name>base</name>
          <desc>Home base in which to buy. If the CalcValue function is defined in obj, the return value of CalcValue is used.</desc>
          <optional />
        </param>
        <param>
          <type>int</type>
          <name>for_player</name>
          <desc>Player to whom the value applies. If the CalcValue function is defined in obj, the return value of CalcValue is used in this case also.</desc>
          <optional />
        </param>
      </params>
    </syntax>
    <desc>Determines the value of an object. With idDef specified, the standard value of the original object definition is returned, otherwise the current value of the specified object (obj) or the calling object if obj is 0.<br/>An object's value is determined as follows: with pObj specified it is first checked whether the CalcValue function is defined in the object's script and if so, it is evaluated. Otherwise, the definition value is used (see below). The resulting value is then reduced according to the object's completion.<br/>Dead animals or clonks always have value 0.<br/>The definition value is determined as follows: if the function CalcDefValue is defined in the definition script, it is evaluated. Otherwise, the value overload from Scenario.txt is used, if present. Otherwise, the standard value from DefCore is used.</desc>
    <remark>The two parameters base and for_player are designed for use in special trading in individual scenarios and are only processed by CalcValue/CalcDefValue calls.</remark>
    <examples>
      <example>
        <code>var value=GetValue();
<funclink>while</funclink> (value--&gt;0) <funclink>CreateContents</funclink>(Rock);
<funclink>RemoveObject</funclink>(true);</code>
        <text>Object script: the object creates as many rocks as it is worth and then self-destructs (expelling the rocks).</text>
      </example>
    </examples>
    <related>
      <funclink>GetWealth</funclink>
      <funclink>SetWealth</funclink>
    </related>
  </func>
  <author>Sven2</author><date>2003-03</date>
</funcs>
