=== isuhao/openclonk-debian/docs/clonk.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!ENTITY % text "a | img | emlink | funclink | em | code | strong">

<!ELEMENT funcs (func+, (author, date)+)>
  <!ELEMENT func           (title, deprecated?, category, subcat*, version, deprecated?, syntax, desc, remark*, examples?, related?)>
    <!ELEMENT title        (#PCDATA)>
    <!ELEMENT category     (#PCDATA)>
    <!ELEMENT subcat       (#PCDATA)>
    <!ELEMENT version      (#PCDATA | extversion)*>
      <!ELEMENT extversion (#PCDATA)>
    <!ELEMENT deprecated   EMPTY>
    <!ELEMENT internal     EMPTY>
    <!ELEMENT syntax       (rtype, params*)>
      <!ELEMENT rtype      (#PCDATA)>
      <!ELEMENT params     (#PCDATA | param)*>
        <!ELEMENT param    (type?, optional?, name, optional?, desc, optional?)>
          <!ELEMENT name   (#PCDATA)>
          <!ELEMENT type   (#PCDATA)>
          <!ELEMENT desc   (#PCDATA | br | ul | li | table | %text;)*>
          <!ELEMENT optional EMPTY>
    <!ELEMENT remark       (#PCDATA | br | ul | li | table | %text;)*>
    <!ELEMENT examples     (example+)>
      <!ELEMENT example    (code | text)*>
        <!ELEMENT code     (#PCDATA | funclink | emlink | em | strong)*>
        <!ELEMENT text     (#PCDATA | br | ul | li | table | %text;)*>
    <!ELEMENT related      (funclink | emlink)+>
      <!ELEMENT funclink   (#PCDATA)>
      <!ELEMENT emlink     (#PCDATA)>
        <!ATTLIST emlink href CDATA #REQUIRED>
  <!ELEMENT author         (#PCDATA)>
  <!ELEMENT date           (#PCDATA)>
<!ELEMENT doc (title, (h | text | dl | part | code | author | date | img)*)>
  <!ELEMENT part (h | text | part | code | dl)*>

<!ELEMENT br EMPTY>

<!ELEMENT table (#PCDATA | caption | rowh | row | bitmask)*>
  <!ELEMENT caption (#PCDATA)>
    <!ATTLIST caption
      id ID #IMPLIED>
  <!ELEMENT row   (#PCDATA | col | literal_col)*>
    <!ATTLIST row
      id ID #IMPLIED>
  <!ELEMENT rowh  (#PCDATA | col | literal_col)*>
  <!ELEMENT col   (#PCDATA | %text;)*>
    <!ATTLIST col
      colspan CDATA #IMPLIED>
  <!ELEMENT literal_col   (#PCDATA | %text;)*>
    <!ATTLIST literal_col
      colspan CDATA #IMPLIED>
  <!ELEMENT bitmask (#PCDATA)>

<!ELEMENT ul    (#PCDATA | li)*>
  <!ELEMENT li    (#PCDATA | br | %text;)*>

<!ELEMENT dl    (#PCDATA | dd | dt)*>
  <!ELEMENT dt    (#PCDATA | br | %text;)*>
    <!ATTLIST dt
      id ID #IMPLIED>
  <!ELEMENT dd    (#PCDATA | text | code)*>

<!ELEMENT em    (#PCDATA)>
<!ELEMENT strong (#PCDATA)>

<!ELEMENT h     (#PCDATA)>
  <!ATTLIST h
    id ID #IMPLIED>

<!ELEMENT img   EMPTY>
  <!ATTLIST img
    src CDATA #REQUIRED
    width CDATA "0"
    height CDATA "0"
    id ID #IMPLIED>

<!ELEMENT a     (#PCDATA)>
  <!ATTLIST a
    href CDATA #REQUIRED>

=== isuhao/openclonk-debian/docs/sdk/script/fn/GetMass.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE funcs
  SYSTEM '../../../clonk.dtd'>
<?xml-stylesheet type="text/xsl" href="../../../clonk.xsl"?>
<funcs>
  <func>
    <title>GetMass</title>
    <category>Objects</category>
    <subcat>Status</subcat>
    <version>4.6.5.0 CP<extversion>4.9.1.0 GWE</extversion></version>
    <syntax><rtype>int</rtype></syntax>
    <desc>Returns the mass of the calling objects (including the mass of all its contents) or the calling definition.</desc>
    <examples>
      <example>
        <code>/* Wird bei klick auf Spezial aufgerufen */
protected func ControlSpecial()
{
	// Magersüchtig?
	if(<funclink>GetMass</funclink>() &lt; 50) // Normalmasse des Clonk: 50
		// Magensäure frisst sich nach aussen
		<funclink>CastPXS</funclink>(&quot;Acid&quot;, 150, 30);
<funclink>return</funclink> 1;
}		
				</code>
        <text>Twiggy</text>
      </example>
    </examples>
  </func>
  <author>wipfmetz</author><date>2002-08</date>
  <author>Sven2</author><date>2003-04</date>
</funcs>

=== isuhao/openclonk-debian/docs/sdk/script/fn/DigFree.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE funcs
  SYSTEM '../../../clonk.dtd'>
<?xml-stylesheet type="text/xsl" href="../../../clonk.xsl"?>
<funcs>
  <func>
    <title>DigFree</title>
    <category>Landscape</category>
    <version>5.1 OC</version>
    <syntax>
      <rtype>int</rtype>
      <params>
        <param>
          <type>int</type>
          <name>x</name>
          <desc>X coordinate</desc>
        </param>
        <param>
          <type>int</type>
          <name>y</name>
          <desc>Y coordinate</desc>
        </param>
        <param>
          <type>int</type>
          <name>radius</name>
          <desc>Radius</desc>
        </param>
		<param>
          <type>bool</type>
          <name>no_dig2objects</name>
          <desc>Prevent objects from being dug out</desc>
        </param>
      </params>
    </syntax>
    <desc>Makes a circular hole in semi-solid materials. The return value is the amount of pixels that were dug free. If no_dig2objects is true, the dug out material does neither create objects according to the Dig2Objects in the <emlink href="material/ocm.html">*.ocm</emlink> nor will the amount be stored in the internal buffer.</desc>
    <examples>
      <example>
        <code>DigFree(700, 1500, 5);</code>
        <text>Makes a small hole in the middle of the landscape.</text>
      </example>
    </examples>
    <related>
      <funclink>DigFreeRect</funclink>
      <funclink>Explode</funclink>
    </related>
  </func>
  <author>jwk</author><date>2002-04</date>
</funcs>

=== isuhao/openclonk-debian/docs/sdk/script/fn/ClearScheduleCall.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE funcs
  SYSTEM '../../../clonk.dtd'>
<?xml-stylesheet type="text/xsl" href="../../../clonk.xsl"?>
<funcs>
  <func>
    <title>ClearScheduleCall</title>
    <category>Script</category>
    <version>4.9.5.0 CE</version>
    <syntax>
      <rtype>bool</rtype>
      <params>
        <param>
          <type>object</type>
          <name>obj</name>
          <desc>Object for which to cancel scheduled function calls. Can be 0 for the calling object.</desc>
        </param>
        <param>
          <type>string</type>
          <name>function</name>
          <desc>Name of the scheduled function.</desc>
        </param>
      </params>
    </syntax>
    <desc>Cancels function calls which has been scheduled by <funclink>ScheduleCall</funclink>. All scheduled calls to the specified function will be cancelled.</desc>
    <examples>
      <example>
        <code>ClearScheduleCall(<funclink>FindObject</funclink>(Clonk), &quot;Redefine&quot;);</code>
        <text>Cancels all scheduled calls to the function "Redefine" for the first clonk.</text>
      </example>
    </examples>
    <related>
      <funclink>Schedule</funclink>
      <funclink>ScheduleCall</funclink>
    </related>
  </func>
  <author>PeterW</author><date>2005-08</date>
</funcs>

=== isuhao/openclonk-debian/docs/sdk/script/fn/SetAttachBones.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE funcs
  SYSTEM '../../../clonk.dtd'>
<?xml-stylesheet type="text/xsl" href="../../../clonk.xsl"?>
<funcs>
  <func>
    <title>SetAttachBones</title>
    <category>Objects</category>
    <subcat>Display</subcat>
    <version>4.10.0.0 OC</version>
    <syntax>
      <rtype>bool</rtype>
      <params>
        <param>
          <type>int</type>
          <name>attach_number</name>
          <desc>Number of the attached mesh. The return value of <funclink>AttachMesh</funclink> provides such a number.</desc>
        </param>
        <param>
          <type>string</type>
          <name>parent_bone</name>
          <desc>Bone of the calling object at which to attach the mesh.</desc>
          <optional />
        </param>
        <param>
          <type>string</type>
          <name>child_bone</name>
          <desc>Bone of the object to be attached.</desc>
          <optional />
        </param>
      </params>
    </syntax>
    <desc>If a mesh was previously attached to another mesh then this function can be used to change one or both of the bones at which they are attached. To only change a single bone the other parameter can be set to <code>nil</code>.</desc>
    <examples>
      <example>
        <code>func FxIntCarryBowStart(object target, int number)
{
	<funclink>EffectVar</funclink>(0, target, number) = target-&gt;<funclink>AttachMesh</funclink>(Bow, &quot;pos_hand1&quot;, &quot;main&quot;);
	<funclink>EffectVar</funclink>(1, target, number) = true;
}

func FxIntCarryBowTimer(object target, int number)
{
	<funclink>if</funclink>(<funclink>EffectVar</funclink>(1, target, number))
		target-&gt;<funclink>SetAttachBones</funclink>(<funclink>EffectVar</funclink>(0, target, number), &quot;pos_hand2&quot;, nil);
	else
		target-&gt;<funclink>SetAttachBones</funclink>(<funclink>EffectVar</funclink>(0, target, number), &quot;pos_hand1&quot;, nil);
	<funclink>EffectVar</funclink>(1, target, number) = !<funclink>EffectVar</funclink>(1, target, number);
}</code>
        <text>Script for an <emlink href="script/Effects.html">effect</emlink>: Initially the clonk carries a bow and for each timer call the bow is switched from its left hand to its right hand or vice versa.</text>
      </example>
    </examples>
    <related>
      <funclink>AttachMesh</funclink>
      <funclink>DetachMesh</funclink>
      <funclink>SetAttachTransform</funclink>
    </related>
  </func>
  <author>Clonk-Karl</author><date>2010-04</date>
</funcs>

=== isuhao/openclonk-debian/docs/sdk/script/fn/Random.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE funcs
  SYSTEM '../../../clonk.dtd'>
<?xml-stylesheet type="text/xsl" href="../../../clonk.xsl"?>
<funcs>
  <func>
    <title>Random</title>
    <category>Arithmetics</category>
    <version>4.6.5.0 CP</version>
    <syntax>
      <rtype>int</rtype>
      <params>
        <param>
          <type>int</type>
          <name>max</name>
          <desc>Maximum value</desc>
        </param>
      </params>
    </syntax>
    <desc>Yields a random number from 0 to max-1. The returned value cannot be greater than 32767, however.</desc>
    <examples>
      <example>
        <code>protected func Hit()
{
  <funclink>if</funclink>(!Random(60)) <funclink>Explode</funclink>(Random(10)+1);
}
        </code>
        <text>Explodes the object with a probability of 1:60. The explosion radius is a random value from 1 to 10.</text>
      </example>
    </examples>
    <related><funclink>RandomX</funclink></related>
  </func>
  <author>jwk</author><date>2002-06</date>
</funcs>

=== isuhao/openclonk-debian/docs/sdk/script/fn/VIS_All.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE funcs
  SYSTEM '../../../clonk.dtd'>
<?xml-stylesheet type="text/xsl" href="../../../clonk.xsl"?>
<funcs>
  <func>
    <title>VIS_All</title>
    <category>Objects</category>
    <subcat>Visibility</subcat>
    <version>4.9.1.0 GWE</version>
    <syntax><rtype>int</rtype></syntax>
    <desc>Constant for <funclink>GetVisibility</funclink>/<funclink>SetVisibility</funclink>. The object is visible for all. This is the default value 0 and kann logically not be combined with other VIS_x values.</desc>
    <remark>This value is also defined as a constant. Thus the parameter brackets can be omitted.</remark>
    <examples>
      <example>
        <code>for(var obj in FindObjects()) SetVisibility(VIS_All, obj);</code>
        <text>Makes all objects visible.</text>
      </example>
    </examples>
    <related>
      <funclink>GetVisibility</funclink>
      <funclink>SetVisibility</funclink>
      <funclink>VIS_None</funclink>
      <funclink>VIS_Owner</funclink>
      <funclink>VIS_Allies</funclink>
      <funclink>VIS_Enemies</funclink>
      <funclink>VIS_God</funclink>
      <funclink>VIS_Local</funclink>
    </related>
  </func>
  <author>Sven2</author><date>2001-11</date>
</funcs>

=== isuhao/openclonk-debian/docs/sdk/script/fn/OCF_NotContained.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE funcs
  SYSTEM '../../../clonk.dtd'>
<?xml-stylesheet type="text/xsl" href="../../../clonk.xsl"?>
<funcs>
  <func>
    <title>OCF_NotContained</title>
    <category>Objects</category>
    <subcat>OCF</subcat>
    <version>4.9.1.0 GWE</version>
    <syntax><rtype>int</rtype></syntax>
    <desc>Object character flag: object is outside, not contained.</desc>
    <remark>This value is also defined as a constant. Thus the parameter brackets can be omitted.</remark>
    <remark>For more information and examples regarding these constants see <emlink href="definition/ocf.html">object character flags</emlink>.</remark>
    <related>
      <funclink>GetOCF</funclink>
      <funclink>FindObject</funclink>
      <funclink>Find_NoContainer</funclink>
      <emlink href="definition/ocf.html">Object character flags</emlink>
    </related>
  </func>
  <author>Sven2</author><date>2002-05</date>
</funcs>

=== isuhao/openclonk-debian/docs/sdk/script/fn/CheckEnergyNeedChain.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE funcs
  SYSTEM '../../../clonk.dtd'>
<?xml-stylesheet type="text/xsl" href="../../../clonk.xsl"?>
<funcs>
  <func>
    <title>CheckEnergyNeedChain</title>
    <category>Objects</category>
    <subcat>Status</subcat>
    <version>4.6.5.0 CP</version>
    <syntax><rtype>bool</rtype></syntax>
    <desc>Checks whether any energy user connected to the specified object currently requires energy. The search will also include indirectly connected objects (via multiple lines).</desc>
    <remark>The search is performed only in the direction in which energy is also transferred, meaning from suppliers to users.</remark>
    <examples>
      <example>
        <code><funclink>if</funclink>(CheckEnergyNeedChain()) <funclink>SetAction</funclink>(&quot;Burning&quot;);</code>
        <text>Script for a power plant: if any of the connected users needs energy, the furnace is started.</text>
      </example>
    </examples>
    <related>
      <funclink>EnergyCheck</funclink>
      <funclink>GetEnergy</funclink>
      <funclink>DoEnergy</funclink>
    </related>
  </func>
  <author>Sven2</author><date>2003-06</date>
</funcs>
